# Generated by Django 4.2.30 on 2026-05-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='unknown_faces/%Y/%m/%d/')),
                ('bbox', models.JSONField(default=list, help_text='[x1, y1, x2, y2] in image pixels')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'face_attendance_unknown_face_log',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('face', 'Face Detection'), ('manual', 'Manual')], default='face', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('slot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.person')),
            ],
            options={
                'db_table': 'face_attendance_log',
                'ordering': ['-check_in'],
            },
        ),
    ]
